### ISSUE TITLE
AppRun fails to download emacs on Linux

### ISSUE THREAD

**Issue by bcm0** [mattfidler/EmacsPortable.App#31]

**Comment by mlf176f2** [comment]
No. 

It only run puppy linux off the USB currently.  If you use row filer it will download and build emacs for the version of Linux you are running and then run it from there

**Comment by mlf176f2** [comment]
That is the ROX filer.   I have repeatedly tried to figure out how to portablize Linux executables,  but I haven't figured it out...

**Comment by nokianhunter** [comment]
Thanks for your suggestion. I have the same problem with rox filer: "Can't execute ./configure: file not found." Maybe the download-url has changed.
There is a project to make portable Linux apps and games on github. I'll try something out...

**Comment by nokianhunter** [comment]
Thanks for your suggestion. I have the same problem with rox filer: "Can't execute ./configure: file not found." Maybe the download-url has changed.
There is a project to make portable Linux apps and games on github. I'll try something out...
